name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Run Shellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
  test-versions:
    name: Test installing versions
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Default version
        uses: ./
        id: depcheck-default
        with:
          dir: './test-success'
      - name: Version 1-3-0
        uses: ./
        id: depcheck-1-3-0
        with:
          dir: './test-success'
          version: '1.3.0'
      - name: Version 1-2-0
        uses: ./
        id: depcheck-1-2-0
        with:
          dir: './test-success'
          version: '1.2.0'
      - name: Version 1-0-0
        uses: ./
        id: depcheck-1-0-0
        with:
          dir: './test-success'
          version: '1.0.0'
  test-success:
    name: Test success depcheck
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: depcheck
        uses: ./
        id: depcheck
        with:
          dir: './test-success'
      - name: Validate exit code.
        if: steps.depcheck.outputs.exit_code != 0
        run: |
          echo "Invalid exit code returned from depcheck"
          exit 1
  test-failure:
    name: Test failure depcheck
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: depcheck
        uses: ./
        id: depcheck
        continue-on-error: true
        with:
          dir: './test-failure'
      - name: Validate exit code.
        if: steps.depcheck.outputs.exit_code == 0
        run: |
          echo "Invalid exit code returned from depcheck: ${{ steps.depcheck.outputs.exit_code }}"
          exit 1

